# Generated by Django 3.2.5 on 2021-07-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('inchi', models.CharField(max_length=1024)),
                ('brutto', models.CharField(max_length=256)),
                ('molar_mass', models.FloatField()),
            ],
        ),
    ]
