# Generated by Django 3.2.5 on 2021-08-11 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('name_format', models.JSONField(blank=True, max_length=256)),
                ('structure', models.JSONField(blank=True, max_length=4096)),
                ('mol_block', models.TextField(blank=True)),
                ('molecular_formula', models.CharField(blank=True, max_length=128)),
                ('molar_mass', models.FloatField(blank=True)),
                ('synonym', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cas', models.IntegerField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('hazard_pictograms', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('z', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=3)),
                ('atomic_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ElementAbundance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_of_chemicals', models.BigIntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.element')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('unit_symbol', models.CharField(max_length=32)),
                ('quantity_type', models.CharField(max_length=32)),
                ('basic_unit', models.CharField(max_length=32)),
                ('relation_to_basic', models.FloatField(null=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoragePlace',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('level', models.SmallIntegerField()),
                ('parent', models.IntegerField()),
                ('terminal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StructElementRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.chemical')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.element')),
            ],
            options={
                'unique_together': {('element', 'chemical')},
            },
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
        migrations.AddField(
            model_name='element',
            name='contained_by',
            field=models.ManyToManyField(through='base_app.StructElementRel', to='base_app.Chemical'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='quantity_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_app.quantityunit'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='storage_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_app.storageplace'),
        ),
    ]
