# Generated by Django 3.2.5 on 2024-12-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('name_data', models.JSONField(null=True)),
                ('structure', models.JSONField(null=True)),
                ('mol_block', models.TextField(null=True)),
                ('molecular_formula', models.CharField(max_length=128, null=True)),
                ('molar_mass', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
                ('synonym', models.TextField(null=True)),
                ('synonym_data', models.JSONField(null=True)),
                ('comment', models.TextField(null=True)),
                ('comment_data', models.JSONField(null=True)),
                ('cas', models.PositiveBigIntegerField(null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('hazard_pictograms', models.CharField(max_length=256, null=True)),
                ('when_created', models.DateField(auto_now_add=True)),
                ('when_updated', models.DateField(default=None, null=True)),
                ('barcode', models.PositiveIntegerField(default=None, null=True, unique=True)),
                ('date_time_taken', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_of_occurrences', models.PositiveSmallIntegerField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
            options={
                'verbose_name': 'ManyToMany table with n of atoms field',
            },
        ),
        migrations.CreateModel(
            name='Chemical_Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_of_occurrences', models.PositiveIntegerField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
            options={
                'verbose_name': 'ManyToMany table with n of path occurences field',
            },
        ),
        migrations.CreateModel(
            name='Chemical_Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_of_occurrences', models.PositiveIntegerField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
            options={
                'verbose_name': 'ManyToMany table with n of ring occurences field',
            },
        ),
        migrations.CreateModel(
            name='QuantityUnit',
            fields=[
                ('unit_symbol', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('measure_type', models.CharField(max_length=32)),
                ('relation_to_basic', models.DecimalField(decimal_places=32, max_digits=64)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoragePlace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('level', models.SmallIntegerField()),
                ('parent', models.IntegerField(null=True)),
                ('contains_chemicals', models.BooleanField(default=False)),
                ('path_str', models.CharField(max_length=1024)),
                ('barcode', models.PositiveIntegerField(default=None, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('label', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('n_of_chemicals', models.PositiveBigIntegerField()),
                ('contained_by', models.ManyToManyField(through='chemicals.Chemical_Ring', to='chemicals.Chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('label', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('n_of_chemicals', models.PositiveBigIntegerField()),
                ('contained_by', models.ManyToManyField(through='chemicals.Chemical_Path', to='chemicals.Chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('z', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('symbol', models.CharField(max_length=3, unique=True)),
                ('atomic_weight', models.DecimalField(decimal_places=4, max_digits=7)),
                ('n_of_chemicals', models.PositiveBigIntegerField(default=0)),
                ('contained_by', models.ManyToManyField(through='chemicals.Chemical_Element', to='chemicals.Chemical')),
            ],
            options={
                'ordering': ['z'],
            },
        ),
        migrations.AddField(
            model_name='chemical_ring',
            name='ring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.ring'),
        ),
        migrations.AddField(
            model_name='chemical_path',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.path'),
        ),
        migrations.AddField(
            model_name='chemical_element',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.element'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='quantity_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chemicals.quantityunit'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='storage_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chemicals.storageplace'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='who_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chemical_records', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='who_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_chemical_records', to='profiles.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='chemical_ring',
            unique_together={('ring', 'chemical')},
        ),
        migrations.AlterUniqueTogether(
            name='chemical_path',
            unique_together={('path', 'chemical')},
        ),
        migrations.AlterUniqueTogether(
            name='chemical_element',
            unique_together={('element', 'chemical')},
        ),
    ]
