import time
from base_app.models import StoragePlace


def wait():
    time.sleep(0.2)


# root = StoragePlace.make_root(root_name="root")
root = StoragePlace.objects.get(level=0)


a = StoragePlace.create("Лаб. 416", root, False)
a.save()
wait()
b = StoragePlace.create("Шкаф 1", a, False)
b.save()
wait()
c = StoragePlace.create("Полка 1", b, True)
c.save()
wait()
d = StoragePlace.create("Полка 2", b, True)
d.save()
wait()
e = StoragePlace.create("Полка 3", b, True)
e.save()
wait()
f = StoragePlace.create("Шкаф 2", a, False)
f.save()
wait()
g = StoragePlace.create("Верхняя полка", f, True)
g.save()
wait()
h = StoragePlace.create("Средняя полка", f, True)
h.save()
wait()
i = StoragePlace.create("Нижняя полка", f, True)
i.save()
wait()
j = StoragePlace.create("Холодильник", a, False)
j.save()
wait()
k = StoragePlace.create("Верхняя полка", j, True)
k.save()
wait()
l = StoragePlace.create("Нижняя полка", j, True)
l.save()
wait()
m = StoragePlace.create("Дверь", j, True)
m.save()
wait()
n = StoragePlace.create("Лаб. 401", root, False)
n.save()
wait()
o = StoragePlace.create("Шкаф", n, False)
o.save()
wait()
p = StoragePlace.create("Коробка 1", o, True)
p.save()
wait()
q = StoragePlace.create("Коробка 2", o, True)
q.save()
wait()
r = StoragePlace.create("Верхняя полка", o, True)
r.save()
wait()
s = StoragePlace.create("Холодильник", n, False)
s.save()
wait()
t = StoragePlace.create("Верхняя полка", s, True)
t.save()
wait()
u = StoragePlace.create("Нижняя полка", s, True)
u.save()
wait()
v = StoragePlace.create("Шуфлядка", s, True)
v.save()
wait()
w = StoragePlace.create("Сейф", n, True)
w.save()
wait()
x = StoragePlace.create("Лаб. 425", root, False)
x.save()
wait()
y = StoragePlace.create("Шкаф 1", x, True)
y.save()
wait()
z = StoragePlace.create("Полка 1", y, True)
z.save()
wait()
aa = StoragePlace.create("Полка 2", y, True)
aa.save()
wait()
ab = StoragePlace.create("Полка 3", y, True)
ab.save()
wait()
ac = StoragePlace.create("Холодильник 1", x, False)
ac.save()
wait()
ad = StoragePlace.create("Полка 1", ac, True)
ad.save()
wait()
ae = StoragePlace.create("Полка 2", ac, True)
ae.save()
wait()
af = StoragePlace.create("Холодильник 2", x, False)
af.save()
wait()
ag = StoragePlace.create("Верхняя полка", af, True)
ag.save()
wait()
ah = StoragePlace.create("Средняя полка", af, True)
ah.save()
wait()
ai = StoragePlace.create("Нижняя полка", af, True)
ai.save()
wait()

