storages = [{'id': 1, 'name': 'root', 'level': 0, 'parent': None, 'terminal': False},
 {'id': 2, 'name': 'Лаб. 416', 'level': 1, 'parent': 1, 'terminal': False},
 {'id': 3, 'name': 'Шкаф 1', 'level': 2, 'parent': 2, 'terminal': False},
 {'id': 4, 'name': 'Полка 1', 'level': 3, 'parent': 3, 'terminal': True},
 {'id': 5, 'name': 'Полка 2', 'level': 3, 'parent': 3, 'terminal': True},
 {'id': 6, 'name': 'Полка 3', 'level': 3, 'parent': 3, 'terminal': True},
 {'id': 7, 'name': 'Шкаф 2', 'level': 2, 'parent': 2, 'terminal': False},
 {'id': 8, 'name': 'Верхняя полка', 'level': 3, 'parent': 7, 'terminal': True},
 {'id': 9, 'name': 'Средняя полка', 'level': 3, 'parent': 7, 'terminal': True},
 {'id': 10, 'name': 'Нижняя полка', 'level': 3, 'parent': 7, 'terminal': True},
 {'id': 11, 'name': 'Холодильник', 'level': 2, 'parent': 2, 'terminal': False},
 {'id': 12,
  'name': 'Верхняя полка',
  'level': 3,
  'parent': 11,
  'terminal': True},
 {'id': 13,
  'name': 'Нижняя полка',
  'level': 3,
  'parent': 11,
  'terminal': True},
 {'id': 14, 'name': 'Дверь', 'level': 3, 'parent': 11, 'terminal': True},
 {'id': 15, 'name': 'Лаб. 401', 'level': 1, 'parent': 1, 'terminal': False},
 {'id': 16, 'name': 'Шкаф', 'level': 2, 'parent': 15, 'terminal': False},
 {'id': 17, 'name': 'Коробка 1', 'level': 3, 'parent': 16, 'terminal': True},
 {'id': 18, 'name': 'Коробка 2', 'level': 3, 'parent': 16, 'terminal': True},
 {'id': 19,
  'name': 'Верхняя полка',
  'level': 3,
  'parent': 16,
  'terminal': True},
 {'id': 20,
  'name': 'Холодильник',
  'level': 2,
  'parent': 15,
  'terminal': False},
 {'id': 21,
  'name': 'Верхняя полка',
  'level': 3,
  'parent': 20,
  'terminal': True},
 {'id': 22,
  'name': 'Нижняя полка',
  'level': 3,
  'parent': 20,
  'terminal': True},
 {'id': 23, 'name': 'Шуфлядка', 'level': 3, 'parent': 20, 'terminal': True},
 {'id': 24, 'name': 'Сейф', 'level': 2, 'parent': 15, 'terminal': True},
 {'id': 25, 'name': 'Лаб. 425', 'level': 1, 'parent': 1, 'terminal': False},
 {'id': 26, 'name': 'Шкаф 1', 'level': 2, 'parent': 25, 'terminal': True},
 {'id': 27, 'name': 'Полка 1', 'level': 3, 'parent': 26, 'terminal': True},
 {'id': 28, 'name': 'Полка 2', 'level': 3, 'parent': 26, 'terminal': True},
 {'id': 29, 'name': 'Полка 3', 'level': 3, 'parent': 26, 'terminal': True},
 {'id': 30,
  'name': 'Холодильник 1',
  'level': 2,
  'parent': 25,
  'terminal': False},
 {'id': 31, 'name': 'Полка 1', 'level': 3, 'parent': 30, 'terminal': True},
 {'id': 32, 'name': 'Полка 2', 'level': 3, 'parent': 30, 'terminal': True},
 {'id': 33,
  'name': 'Холодильник 2',
  'level': 2,
  'parent': 25,
  'terminal': False},
 {'id': 34,
  'name': 'Верхняя полка',
  'level': 3,
  'parent': 33,
  'terminal': True},
 {'id': 35,
  'name': 'Средняя полка',
  'level': 3,
  'parent': 33,
  'terminal': True},
 {'id': 36,
  'name': 'Нижняя полка',
  'level': 3,
  'parent': 33,
  'terminal': True}]

users_dict = {
    "johndoe": "John Doe",
    "claudius": "Claudius Allen",
    "melissa_brown": "Melissa Brown",
    "martinchandler": "Martin Chandler",
    "isaac_farmer": "Isaac Farmer",
    "abychto": "Ihar Fomchanka",
    "lisa_freeman": "Lisa Freeman",
    "abram_blackwater": "Abram Blackwater",
    "greg_white": "Greg White",
}

recent = ["abychto",
          "melissa_brown",
          "claudius",
          "greg_white"]
