// Generated by CoffeeScript 2.6.1
/* eslint-disable */;
var Chemical, FrameMaker, ListPoint, Receiver, Storage,
  boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

export var Tree = (function() {
  class Tree {
    constructor(tree_container, input_name) {
      var root;
      this.update_field = this.update_field.bind(this);
      this.tree_container_mouse = this.tree_container_mouse.bind(this);
      this.highlight = this.highlight.bind(this);
      this.unhighlight = this.unhighlight.bind(this);
      this.highlight_only_this = this.highlight_only_this.bind(this);
      this.process_click = this.process_click.bind(this);
      this.highlighted_shift_or_ctrl = this.highlighted_shift_or_ctrl.bind(this);
      this.highlighted_no_key = this.highlighted_no_key.bind(this);
      this.unhighlighted_shift = this.unhighlighted_shift.bind(this);
      this.process_span_list = this.process_span_list.bind(this);
      this.highlight_domain = this.highlight_domain.bind(this);
      this.unhighlighted_ctrl = this.unhighlighted_ctrl.bind(this);
      this.unhighlighted_no_key = this.unhighlighted_no_key.bind(this);
      if (Tree.instances.length >= 2) {
        throw Error("can't create more than 2 tree instances");
      } else if (Tree.instances.length === 1) {
        this.number = 1;
      } else {
        this.number = 0;
      }
      Object.defineProperty(this, "other_instance", {
        get: function() {
          if (Tree.instances.length <= 1) {
            return null;
          } else if (Tree.instances.length === 2 && this.number === 0) {
            return Tree.instances[1];
          } else if (Tree.instances.length === 2 && this.number === 1) {
            return Tree.instances[0];
          }
        }
      });
      this.highlighted_nodes_ids = [];
      this.tree_container = tree_container;
      this.input_node = document.querySelector(`input[name=${input_name}]`);
      this.background = tree_container.querySelector(".background");
      this.foreground = tree_container.querySelector(".foreground");
      root = Receiver.get_root();
      if (root !== "error") {
        this.root_object = new Storage(root.name, Number(root.id), null, this);
      } else {
        this.root_object = new Storage("error", 0, null, this);
      }
      this.root_object.li = this.foreground.querySelector("li");
      this.root_object.span = this.root_object.li.querySelector("span");
      this.root_object.span.addEventListener("dblclick", this.root_object.open_close);
      this.root_object.span.addEventListener("click", this.process_click);
      Tree.instances.push(this);
      this.frame_maker = new FrameMaker(this);
      this.tree_container.addEventListener("mousedown", this.tree_container_mouse);
      this.tree_container.addEventListener("mouseup", this.tree_container_mouse);
      this.tree_container.addEventListener("mousemove", this.tree_container_mouse);
      this.there_was_mousedown = false;
    }

    update_field(new_value) {
      return this.input_node.setAttribute("value", JSON.stringify(new_value));
    }

    tree_container_mouse(event) {
      var i, id_of_node, len, node, ref;
      if (event.target.nodeName !== "SPAN") {
        if (event.type === "mousedown") {
          return this.there_was_mousedown = true;
        } else if (event.type === "mousemove") {
          return this.there_was_mousedown = false;
        } else if (event.type === "mouseup" && this.there_was_mousedown) {
          ref = this.highlighted_nodes_ids;
          for (i = 0, len = ref.length; i < len; i++) {
            id_of_node = ref[i];
            node = this.foreground.querySelector(`span[data-storage_node_id='${id_of_node}']`);
            node.classList.remove("highlighted");
          }
          this.highlighted_nodes_ids = [];
          this.update_field(this.highlighted_nodes_ids);
          return this.there_was_mousedown = false;
        }
      }
    }

    highlight(node_id) {
      var node;
      if (this.highlighted_nodes_ids.indexOf(node_id) === -1) {
        this.highlighted_nodes_ids.push(node_id);
        this.update_field(this.highlighted_nodes_ids);
        node = this.foreground.querySelector(`span[data-storage_node_id='${node_id}']`);
        return node.classList.add("highlighted");
      }
    }

    unhighlight(node_id) {
      var index_in_array, node;
      if (this.highlighted_nodes_ids.indexOf(node_id) !== -1) {
        index_in_array = this.highlighted_nodes_ids.indexOf(node_id);
        this.highlighted_nodes_ids.splice(index_in_array, 1);
        this.update_field(this.highlighted_nodes_ids);
        node = this.foreground.querySelector(`span[data-storage_node_id='${node_id}']`);
        return node.classList.remove("highlighted");
      }
    }

    highlight_only_this(node_id) {
      var i, id_of_node, len, node, ref;
      ref = this.highlighted_nodes_ids;
      for (i = 0, len = ref.length; i < len; i++) {
        id_of_node = ref[i];
        node = this.foreground.querySelector(`span[data-storage_node_id='${id_of_node}']`);
        node.classList.remove("highlighted");
      }
      this.highlighted_nodes_ids = [];
      this.update_field(this.highlighted_nodes_ids);
      return this.highlight(node_id);
    }

    process_click(event) {
      if (event.target.classList.contains("highlighted")) {
        if (event.shiftKey || event.ctrlKey) {
          return this.highlighted_shift_or_ctrl(event);
        } else {
          return this.highlighted_no_key(event);
        }
      } else {
        if (event.shiftKey) {
          return this.unhighlighted_shift(event);
        } else if (event.ctrlKey) {
          return this.unhighlighted_ctrl(event);
        } else {
          return this.unhighlighted_no_key(event);
        }
      }
    }

    highlighted_shift_or_ctrl(event) {
      return this.unhighlight(event.target.dataset.storage_node_id);
    }

    highlighted_no_key(event) {
      if (this.highlighted_nodes_ids.length === 1) {
        return this.unhighlight(event.target.dataset.storage_node_id);
      } else if (this.highlighted_nodes_ids.length > 1) {
        return this.highlight_only_this(event.target.dataset.storage_node_id);
      }
    }

    unhighlighted_shift(event) {
      var i, j, len, len1, level, levels, node, spans_level_list, the_ul, uls_spans_level;
      the_ul = this.foreground.querySelector("ul");
      levels = [[the_ul]];
      while (levels[levels.length - 1].length !== 0) {
        levels = this.process_levels(levels);
      }
      uls_spans_level = null;
      for (i = 0, len = levels.length; i < len; i++) {
        level = levels[i];
        if (level.indexOf(event.target) !== -1) {
          uls_spans_level = level;
          break;
        }
      }
      spans_level_list = [];
      for (j = 0, len1 = uls_spans_level.length; j < len1; j++) {
        node = uls_spans_level[j];
        if (node.tagName === "SPAN") {
          spans_level_list.push(node);
        }
      }
      return this.process_span_list(spans_level_list, event.target);
    }

    process_levels(levels) {
      var children_arr, i, item, last_level, len, new_level;
      last_level = levels[levels.length - 1];
      new_level = [];
      for (i = 0, len = last_level.length; i < len; i++) {
        item = last_level[i];
        children_arr = Array.from(item.children);
        Array.prototype.push.apply(new_level, children_arr);
      }
      levels.push(new_level);
      return levels;
    }

    process_span_list(span_list, event_target) {
      var i, len, node, will_continue;
      will_continue = false;
      for (i = 0, len = span_list.length; i < len; i++) {
        node = span_list[i];
        if (node.classList.contains("highlighted")) {
          will_continue = true;
          break;
        }
      }
      if (!will_continue) {
        return null;
      }
      return this.highlight_domain(span_list, event_target);
    }

    highlight_domain(span_list, event_target) {
      var domain_of_numbers, i, j, k, len, number, ref, ref1, ref2, results, target_number;
      domain_of_numbers = [];
      target_number = span_list.indexOf(event_target);
      for (number = i = ref = target_number; (ref <= 0 ? i <= 0 : i >= 0); number = ref <= 0 ? ++i : --i) {
        if (span_list[number].classList.contains("highlighted")) {
          break;
        } else {
          domain_of_numbers.push(number);
          continue;
        }
      }
      if (target_number < span_list.length - 1) {
        for (number = j = ref1 = target_number + 1, ref2 = span_list.length - 1; (ref1 <= ref2 ? j <= ref2 : j >= ref2); number = ref1 <= ref2 ? ++j : --j) {
          if (span_list[number].classList.contains("highlighted")) {
            break;
          } else {
            domain_of_numbers.push(number);
            continue;
          }
        }
      }
      results = [];
      for (k = 0, len = domain_of_numbers.length; k < len; k++) {
        number = domain_of_numbers[k];
        results.push(this.highlight(span_list[number].dataset.storage_node_id));
      }
      return results;
    }

    unhighlighted_ctrl(event) {
      return this.highlight(event.target.dataset.storage_node_id);
    }

    unhighlighted_no_key(event) {
      return this.highlight_only_this(event.target.dataset.storage_node_id);
    }

  };

  Tree.instances = [];

  return Tree;

}).call(this);

Chemical = (function() {
  class Chemical {
    constructor(name, id, parent, tree) {
      this.name = name;
      this.id = id;
      this.parent = parent;
      this.tree = tree;
      this.li = null;
      this.span = null;
      Chemical.chemicals_and_storages[id] = this;
    }

  };

  Chemical.chemicals_and_storages = {};

  return Chemical;

}).call(this);

Storage = class Storage extends Chemical {
  constructor(name, id, parent, tree) {
    super(name, id, parent, tree);
    this.open_close = this.open_close.bind(this);
    this.children = [];
    this.level = null;
    this.is_terminal = false;
    this.is_open = false;
  }

  open_close(event) {
    var children, ul;
    boundMethodCheck(this, Storage);
    this.tree.unhighlight(event.target.dataset.storage_node_id);
    if (this.is_open && event.target === this.span) {
      ul = this.li.querySelector("ul");
      ul.remove();
      this.children = [];
      this.is_open = false;
      this.li.classList.remove("open");
      this.li.classList.add("closed");
    } else {
      if (event.target === this.span) {
        children = Receiver.get_children(this.id);
        this.create_children_from_list(children);
        if (JSON.stringify(children) !== "{}") {
          this.is_open = true;
          this.li.classList.remove("closed");
          this.li.classList.add("open");
        }
      }
    }
    this.tree.frame_maker.destructor();
    return this.tree.frame_maker = new FrameMaker(this.tree);
  }

  create_children_from_list(children) {
    var child, id, li, name, results, span, ul;
    ul = document.createElement("ul");
    this.li.append(ul);
    results = [];
    for (id in children) {
      name = children[id];
      if (isNaN(id)) {
        child = new Chemical(name, id, this, this.tree);
      } else {
        child = new Storage(name, Number(id), this, this.tree);
      }
      this.children.push(child);
      li = document.createElement("li");
      span = document.createElement("span");
      span.textContent = name;
      span.setAttribute("data-storage_node_id", id);
      li.append(span);
      ul.append(li);
      child.li = li;
      child.span = span;
      if (child instanceof Storage) {
        span.addEventListener("dblclick", child.open_close);
        span.addEventListener("click", this.tree.process_click);
        results.push(li.classList.add("closed"));
      } else {
        span.addEventListener("click", this.tree.process_click);
        results.push(li.classList.add("chemical"));
      }
    }
    return results;
  }

};

Receiver = (function() {
  class Receiver {
    //    @call: (parent_id) ->
    //        result = {}
    //        for key of @content
    //            if @content[key].parent == parent_id
    //                result[key] = @content[key].name
    //        return result
    static csrf() {
      var csrfContainer, csrfInput;
      if (this.debug) {
        return "";
      } else {
        csrfContainer = document.querySelector("#csrf");
        csrfInput = csrfContainer.querySelector("input");
        return csrfInput.getAttribute("value");
      }
    }

    static tree_address() {
      if (this.debug) {
        return "http://127.0.0.1:5000/";
      } else {
        return window.location.href;
      }
    }

    static get_children(parent_id) {
      var form_to_send, id, received_str, result, returned_obj, xhr;
      if (!parent_id in this.content) {
        throw Error("No such parent_id in @content");
      }
      if (this.content[parent_id].terminal === true) {
        return {};
      }
      form_to_send = new FormData();
      form_to_send.append("give_children_of", parent_id);
      xhr = new XMLHttpRequest();
      xhr.open("POST", this.tree_address(), false);
      xhr.setRequestHeader("X-CSRFToken", this.csrf());
      try {
        xhr.send(form_to_send);
        if (xhr.status === 200) {
          received_str = xhr.response;
          result = JSON.parse(received_str);
          returned_obj = {};
          for (id in result) {
            returned_obj[id] = result[id][0];
            this.content[id] = {
              name: result[id][0],
              parent: parent_id,
              terminal: result[id][1]
            };
          }
          return returned_obj;
        } else {
          return "error";
        }
      } catch (error) {
        return "error";
      }
    }

    static record_creation() {
      return null;
    }

    static get_root() {
      var form_to_send, received_obj, received_str, root_id, root_name, root_terminal, xhr;
      form_to_send = new FormData();
      form_to_send.append("give_root", "");
      xhr = new XMLHttpRequest();
      xhr.open("POST", this.tree_address(), false);
      xhr.setRequestHeader("X-CSRFToken", this.csrf());
      try {
        xhr.send(form_to_send);
        if (xhr.status === 200) {
          received_str = xhr.response;
          received_obj = JSON.parse(received_str);
          root_id = Object.keys(received_obj)[0];
          root_name = received_obj[root_id][0];
          root_terminal = received_obj[root_id][1];
          Receiver.content[root_id] = {
            name: root_name,
            parent: null,
            terminal: root_terminal
          };
          return {
            id: root_id,
            name: root_name
          };
        } else {
          return "error";
        }
      } catch (error) {
        return "error";
      }
    }

  };

  Receiver.content = {};

  // content format: {1: {name: "One", parent: 0, terminal: false}}
  // where 1 is storage id
  Receiver.debug = true;

  return Receiver;

}).call(this);

FrameMaker = class FrameMaker {
  constructor(tree) {
    this.destructor = this.destructor.bind(this);
    this.make_li_list = this.make_li_list.bind(this);
    this.send_event = this.send_event.bind(this);
    this.mousedown_processor = this.mousedown_processor.bind(this);
    this.mousemove_processor = this.mousemove_processor.bind(this);
    this.check_for_intersections = this.check_for_intersections.bind(this);
    this.mouseup_leave_processor = this.mouseup_leave_processor.bind(this);
    this.tree = tree;
    this.anchor = {
      x: 0,
      y: 0
    };
    this.background = tree.background;
    this.foreground = tree.foreground;
    this.foreground.addEventListener("mousedown", this.send_event);
    this.foreground.addEventListener("mouseup", this.send_event);
    this.foreground.addEventListener("mousemove", this.send_event);
    this.foreground.addEventListener("mouseleave", this.send_event);
    this.back_coords = this.background.getBoundingClientRect();
    this.background.addEventListener("mousedown", this.mousedown_processor);
    this.inner_frame = null;
    this.li_list = this.make_li_list();
  }

  destructor() {
    this.foreground.removeEventListener("mousedown", this.send_event);
    this.foreground.removeEventListener("mouseup", this.send_event);
    this.foreground.removeEventListener("mousemove", this.send_event);
    this.foreground.removeEventListener("mouseleave", this.send_event);
    this.background.removeEventListener("mousedown", this.mousedown_processor);
    this.anchor = null;
    this.background = null;
    this.foreground = null;
    this.back_coords = null;
    this.inner_frame = null;
    return this.li_list = null;
  }

  make_li_list() {
    var all_spans, element, i, len, list_point, span_list;
    span_list = [];
    all_spans = this.foreground.querySelectorAll("span");
    for (i = 0, len = all_spans.length; i < len; i++) {
      element = all_spans[i];
      list_point = new ListPoint(element, this.tree);
      span_list.push(list_point);
    }
    return span_list;
  }

  send_event(event) {
    var new_event;
    new_event = new MouseEvent(event.type, {
      bubbles: false,
      cancelable: false,
      clientX: event.clientX,
      clientY: event.clientY
    });
    return this.background.dispatchEvent(new_event);
  }

  mousedown_processor(event) {
    var style_value;
    this.anchor.x = event.clientX - this.back_coords.left;
    this.anchor.y = event.clientY - this.back_coords.top;
    if (this.inner_frame) {
      this.inner_frame.remove();
    }
    this.inner_frame = document.createElement("div");
    this.background.prepend(this.inner_frame);
    style_value = `margin-top: ${this.anchor.y}px; margin-left: ` + `${this.anchor.x}px; width: ${0}px; height: ${0}px;`;
    this.inner_frame.setAttribute("style", style_value);
    this.inner_frame.classList.add("figure");
    this.background.addEventListener("mousemove", this.mousemove_processor);
    this.background.addEventListener("mouseup", this.mouseup_leave_processor);
    return this.background.addEventListener("mouseleave", this.mouseup_leave_processor);
  }

  mousemove_processor(event) {
    var height, margin_left, margin_top, style_value, width, x, y;
    x = event.clientX - this.back_coords.left;
    y = event.clientY - this.back_coords.top;
    margin_left = Math.min(x, this.anchor.x);
    margin_top = Math.min(y, this.anchor.y);
    width = Math.max(x, this.anchor.x) - margin_left;
    height = Math.max(y, this.anchor.y) - margin_top;
    style_value = `margin-top: ${margin_top}px; margin-left: ` + `${margin_left}px; ` + `width: ${width}px; height: ${height}px;`;
    this.inner_frame.setAttribute("style", style_value);
    return this.check_for_intersections(margin_left, margin_top, margin_left + width, margin_top + height);
  }

  check_for_intersections(left, top, right, bottom) {
    var i, len, list_point, ref, results;
    ref = this.li_list;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      list_point = ref[i];
      results.push(list_point.check(left, top, right, bottom, this.back_coords));
    }
    return results;
  }

  mouseup_leave_processor(event) {
    this.inner_frame.remove();
    this.inner_frame = null;
    this.background.removeEventListener("mousemove", this.mousemove_processor);
    this.background.removeEventListener("mouseup", this.mouseup_leave_processor);
    return this.background.removeEventListener("mouseleave", this.mouseup_leave_processor);
  }

};

ListPoint = class ListPoint {
  constructor(node, tree) {
    this.check = this.check.bind(this);
    this.node = node;
    this.tree = tree;
    this.rectangle = node.getBoundingClientRect();
    this.highlighted = false;
  }

  check(left, top, right, bottom, back_coords) {
    var ref, ref1, ref2, ref3, storage_node_id;
    if (((top < (ref = this.rectangle.top - back_coords.top) && ref < bottom) || (top < (ref1 = this.rectangle.bottom - back_coords.top) && ref1 < bottom)) && ((left < (ref2 = this.rectangle.left - back_coords.left) && ref2 < right) || (left < (ref3 = this.rectangle.right - back_coords.left) && ref3 < right))) {
      if (this.highlighted === false) {
        this.node.classList.add("highlighted");
        this.highlighted = true;
        storage_node_id = this.node.dataset.storage_node_id;
        return this.tree.highlight(storage_node_id);
      }
    } else {
      if (this.highlighted === true) {
        this.node.classList.remove("highlighted");
        this.highlighted = false;
        storage_node_id = this.node.dataset.storage_node_id;
        return this.tree.unhighlight(storage_node_id);
      }
    }
  }

};

//# sourceMappingURL=trees_editor05.js.map
