from django.urls import path, include
from django.contrib.auth.decorators import login_required

from api.views import (Users,
                       Chemicals,
                       RootStorage,
                       Storages,
                       Favorites,
                       UninitializedChemicals,
                       PathToChemical,
                       Hashtags,
                       Ampersandtags,
                       Tags,
                       TakeChemical,
                       ReturnChemical,
                       UninitializedStorages)


urlpatterns = [
    path('users',
         Users.as_view()),
    path('chemicals',
         Chemicals.as_view({"post": "create"})),
    path('chemicals/<int:pk>',
         Chemicals.as_view({"get": "retrieve",
                            "put": "update",
                            "delete": "destroy"})),
    path('root-storage',
         RootStorage.as_view()),
    path('storages',
         Storages.as_view({"post": "create"})),
    path('storages/<int:pk>',
         Storages.as_view({"get": "retrieve",
                           "put": "update",
                           "delete": "destroy"})),
    path('favorites',
         Favorites.as_view({"get": "list",
                            "post": "create",
                            "put": "update"})),
    path('uninitialized-chemicals',
         UninitializedChemicals.as_view({"get": "list"})),
    path('uninitialized-chemicals/<int:pk>',
         UninitializedChemicals.as_view({"get": "retrieve",
                                         "put": "update"})),
    path('path-to-chemical/<int:pk>',
         PathToChemical.as_view()),
    path('hashtags',
         Hashtags.as_view({"get": "list",
                           "post": "create"})),
    path('hashtags/<str:pk>',
         Hashtags.as_view({"get": "retrieve",
                           "put": "update"})),
    path('ampersandtags',
         Ampersandtags.as_view({"get": "list",
                                "post": "create"})),
    path('ampersandtags/<str:pk>',
         Ampersandtags.as_view({"get": "retrieve",
                                "put": "update"})),
    path('tags',
         Tags.as_view()),
    path('take-chemical',
         TakeChemical.as_view()),
    path('return-chemical',
         ReturnChemical.as_view()),
    path('uninitialized-storages',
         UninitializedStorages.as_view({"get": "list"})),
    path('uninitialized-storages/<int:pk>',
         UninitializedStorages.as_view({"put": "update"})),
]
